name: Conventional commitses

on:
  pull_request:
  merge_group:

jobs:
  conventional-commits-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Conventional Commit - Action
        uses: webiny/action-conventional-commits@0cc64c05ba23b8179973090d3509f31dba971afb # v1.2.0
