name: Renovate config validator

on:
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  lint-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Use Node.js 21
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Install renovate
        run: npm i renovate
      - name: run renovate-config-validator
        run: ./node_modules/renovate/dist/config-validator.js --strict
